# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e818bb43a2e60d0761b1e1751f42839b8cfc0347aa2edbccb32d06589afa566d9fb30d4fc797f985e45eb4fee4b41c24f1ce4878aa40d291a62232416e346e41

test:
  secret_key_base: 6d7ef357a2892a902af8c72cd0af796a25360f13c24b83415a8dcdd09d0d736f1d54684889f9240fe2d40b5b47045f06ea3e56dbbe44615bf7d454d013c9cd12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
